#!/bin/bash
# Installer for ThePAK

source etc/banner
# Banner Add
echo -e "executing: ${LIGHTGREEN}SETUP${NOCOLOR}"
echo "-----------------------"
# Setup directory for Requirements
quickbms_dir=$PREFIX/share/quickbms
sd=/storage/emulated/0/download
tx=$HOME/ThePaker-3.45

function redirect {
 echo -e "${LIGHTGREEN}STARTING THEPAK${NOCOLOR}"
 echo -ne '#####                     (33%)\r'
 sleep 1
 echo -ne '#############             (66%)\r'
 sleep 1
 echo -ne '#######################   (100%)\r'
 echo -ne '\n'
 chmod +x quickbms etc/tools.bms ThePaker-3.45
bash ThePaker-3.45
}

function quickbms_check {
  echo -e "${YELLOW}Checking required program..${NOCOLOR}"
  FILE=$quickbms_dir/quickbms
  if [ -f "$FILE" ]; then
      echo -e "${LIGHTGREEN}Program has been installed.${NOCOLOR}"
      chmod +x quickbms etc/tools.bms ThePaker-3.45
      redirect
  else 
      echo -e "${RED}PROGRAM NOT FOUND.${NOCOLOR}"
      quickbms_install
      chmod +x quickbms etc/tools.bms thepakv2.1
  fi
}
function nextinstaller {
cd $tx
unzip -qq quickbms_linux.zip
sleep 1
rm -rf $PREFIX/share/quickbms
sleep 1
mkdir $PREFIX/share/quickbms
sleep 1
chmod +x quickbms_4gb_files
sleep 1
yes | cp -rf quickbms_4gb_files $PREFIX/share/quickbms
sleep 1
chmod +x quickbms
sleep 1
yes | cp -rf quickbms $PREFIX/share/quickbms
sleep 1
chmod +x etc/tools.bms ThePaker-3.45
sleep 1
}

function testbmsm {
echo "checking file .Zip"
FILE=$sd/quickbms_linux.zip
  if [ -f "$FILE" ]; then
      echo " file founded"
      cp -rf $sd/quickbms_linux.zip $tx
      nextinstaller
  else 
      clear
      echo -e "${RED}THE FILE IS NOT FOUND${NOCOLOR}"
      quickbms_manual
  fi
}

function testbmsauto {
echo "checking downloaded program"
sleep 1
FILE=quickbms_linux.zip
  if [ -f "$FILE" ]; then
      echo " file founded"
      nextinstaller
  else 
      clear
      echo -e "${RED}THE FILE IS NOT FOUND${NOCOLOR}"
      quickbms_install
  fi
}

function quickbms_manual {
  clear
  echo ""
  echo "http://aluigi.altervista.org/papers/quickbms_linux.zip"
  echo -e "${RED} first download file from link above ${NOCOLOR}"
  echo -e "${GREEN}after download that paste the file in download folder ${NOCOLOR}"
cd $sd
prompt="Please select a file quick bms :"
options=( $(find *.zip) )

PS3="$prompt "
select bms in "${options[@]}" "Quit" ; do 
    if (( REPLY == 1 + ${#options[@]} )) ; then
        exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        echo  "You picked $bms which is file quickbms file"
         testbmsm
    else
        echo "Invalid option. Try another one."
    fi
done
cd $tx
}

function quickbms_auto {
echo "AUTO INSTALLATION METHOD USED"
echo "Please WAIT"
echo "this process depends on your signal"
echo " if it take to long please press CTRL + C"
sleep 2
echo "starting"
cd $tx
if [[ ! -f "quickbms_linux.zip" ]]; then
wget http://aluigi.altervista.org/papers/quickbms_linux.zip
echo " checking..."
testbmsauto
else
testbmsauto
fi
}

function quickbms_install {
echo -e "CHOOSE PROGRAM INSTALLER METHOD"
echo "MAKE SURE YOU HAVE GREAT CONNECTION WHEN CHOOSE AUTO"
echo "because the process Will be taking longer"
PS3='Please enter your CHOOSE: '
options=("Auto" "Manual")
select pategk in "${options[@]}"
do
    case $pategk in
        "Auto")
            quickbms_auto
            ;;
        "Manual")
            quickbms_manual
            ;;
        *) echo "invalid option $REPLY";;
    esac
done 
}

#Checking Required Pakcages
echo -e "${YELLOW}Checking Required packages${NOCOLOR}"

packages=("wget" "unzip" "curl" "x11-repo" "qemu-system-i386" "qemu-user-i386")

for pkg in ${packages[@]}; do

    is_pkg_installed=$(dpkg-query -W --showformat='${Status}\n' ${pkg} | grep "install ok installed")

    if [ "${is_pkg_installed}" == "install ok installed" ]; then
        echo -e ${GREEN}${pkg}${NOCOLOR} is installed.
    else [ "" = "${is_pkg_installed}" ];
     echo -e "${RED}No ${pkg}. Setting up ${pkg}.${NOCOLOR}" 
    pkg install ${pkg} -y
    fi
done
quickbms_check
